#!/bin/bash
chmod +x createTags createMainTagInProjectRoot delTags delTagsFromlnInclude dirTags 

echo "Copying createTags, createMainTagInProjectRoot, delTags and dirTags to: " 
echo $WM_PROJECT_USER_DIR
echo 
cp createTags createMainTagInProjectRoot delTags delTagsFromlnInclude dirTags $WM_PROJECT_USER_DIR
echo "Copying createTags, createMainTagInProjectRoot, deltags, delTagsFromlnInclude and dirTags to: " 
echo $WM_PROJECT_DIR
echo 
cp createTags createMainTagInProjectRoot delTags delTagsFromlnInclude dirTags $WM_PROJECT_DIR

echo "Go to "
echo $WM_PROJECT_USER_DIR
cd $WM_PROJECT_USER_DIR
echo "Deleting old .tags files ..."
echo
./delTags
echo "Running ./createTags ..."
./createTags
echo "Running ./createMainTagInProjectRoot ..."
./createMainTagInProjectRoot
#echo "Deleting .tags from lnInclude directories ..."
#./delTagsFromlnInclude

echo "Go to "
echo $WM_PROJECT_DIR
cd $WM_PROJECT_DIR
echo "Deleting old .tags files ..."
echo
./delTags
echo "Running ./createTags ..."
./createTags
echo "Running ./createMainTagInProjectRoot ..."
./createMainTagInProjectRoot
#echo "Deleting .tags from lnInclude directories ..."
#./delTagsFromlnInclude

