#!/bin/bash
ctags --file-scope=no --extra=+qf --fields=+l --exclude=.git --exclude=bin --exclude=platforms --exclude=build --exclude=doc --exclude=etc --exclude=modules --exclude=ThirdParty --exclude=tutorials --exclude=wmake -Rf .tags .
